language: csharp
solution: Amockibia.sln
sudo: required
dotnet: 2.2
mono: none
os:
  - linux
dist: xenial

before_script:
  - dotnet restore

script:
  - dotnet build
  - dotnet test ./test/Amockibia.Test/Amockibia.Test.csproj
